<Project Sdk="Microsoft.NET.Sdk">

  <!-- General stuff -->
  
  <PropertyGroup>
    <TargetFrameworks>netstandard1.1;netstandard1.3;netstandard2.1;net46;net462;net47;netcoreapp3.0;net5.0;net7.0</TargetFrameworks>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <ProduceReferenceAssembly>True</ProduceReferenceAssembly>
    <DebugType>portable</DebugType>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <CheckNotRecommendedTargetFramework>false</CheckNotRecommendedTargetFramework>
  </PropertyGroup>
  
  <!-- NuGet package customization. -->
  
  <PropertyGroup>
    <Title>Nerd_STF</Title>
    <Version>3.2.0</Version>
    <Authors>That_One_Nerd</Authors>
    <Description>A general-purpose mathematics library for C#.</Description>
    <PackageProjectUrl>https://github.com/That-One-Nerd/Nerd_STF</PackageProjectUrl>
    <PackageIcon>Logo Square.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryUrl>https://github.com/That-One-Nerd/Nerd_STF</RepositoryUrl>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <IncludeSymbols>True</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <PackageTags>c#;csharp;c sharp;math;mathematics;mathametics;maths;color;rgb;rgba;cmyk;cmyka;hsv;hsva;calculus;linear algebra;linalg;linearalgebra;matrix;matrix2x2;matrix 2x2;matrix3x3;matrix 3x3;matrix4x4;matrix 4x4;matrix multiplication;vector;vector2d;vector3d;vector2;vector3;float2;float3;float4;int2;int3;int4;angle;geometry;vert;line;polygon;triangle;quadrilateral;sphere;circle;number system;numbersystem;complex numbers;complex;2d numbers;2dnumbers;quaternions;4d numbers;4dnumbers;equation;equations;polynomial;quadratic;linear equation;discrete mathematics;discrete math;set notation;relation;discrete;ycbcr;ypbpr;ycc</PackageTags>
    
    <!-- Sorry this is stupidly long, wish I could have linked a markdown file instead. -->
    <PackageReleaseNotes>Hi! This update spent a while idle before I got around to releasing it, whoops. Here, we're focusing on linear algebra changes.

## But first, Unit Tests!

I finally got around to experimenting with a test suite. I'm fairly new to this whole schpeel, so some of my tests might not be great. And there also aren't a ton right now. But I'll add many more over time. Hopefully I'll eventually get to testing nearly everything in Nerd_STF. But for now, it's cool to see the little check mark next to the commit.

One of the reasons I started writing tests is because I've had plenty of incidents where I missed bugs that occurred down the line when I would change a function. This hopefully prevents that.

Now the .sln file is finally exposed to the repo. Previously, I've had to hide it because my "messing around" project would be referenced and would cause compiler errors. I've replaced the messing around project with this new test project.

## More Matrix Operations

Like I said, this update concerns itself mainly with linear algebra. Some concepts have been added from that field of mathematics. Namely, I re-implemented the `SwapRows()`, `ScaleRow()`, and `AddRow()` operations from the 2.x versions. Here, `SwapRows(int, int)` swaps two rows of a matrix, `ScaleRow(int, double)` scales one by a certain factor, and `AddRow(int, double, int)` adds a scaled version of one row to another. In general, they're all basic row operations for matrices.

In addition, I also implemented a basic Row-Echelon solver. It's a simple Gaussian reduction algorithm and it is by no means perfect, but it kind of works. I may well make a better one in the future.

&gt; [!NOTE]
&gt; The row-echelon solver is only defined in the dynamic `Matrix` class. Call it using `Matrix.GaussElimination()`.

Range operations also are implemented in all matrix types now. You can use range operators to get particular rows and columns from a Matrix. Can be fairly useful in some circumstances. Here's an example:
```csharp
using Nerd_STF.Mathematics.Algebra;

// r  c 0: 1: 2:
// 0: [ 1, 2, 3 ]
// 1: [ 4, 5, 6 ]
// 2: [ 7, 8, 9 ]
Matrix m = new((3, 3), (x, y) =&gt; x * 3 + y + 1);

Matrix sub = m[1..3, 0..^1];
// Output:
// [ 4, 5 ]
// [ 7, 8 ]
```

Remember that matrix rows and columns are indexed 0-based.

One more thing before we end this part. To improve the use of generics again, I moved all declarations of `IMatrixOperations` into `IMatrix` for simplicity's sake.

---

That's about it. Enjoy the update! I'll be cranking out more unit tests and probably fixing bugs for a while.</PackageReleaseNotes>
  </PropertyGroup>

  <!-- ItemGroup customization based on framework. -->
  <!-- Mostly used to reference system packages that are not included in this version of .NET Standard. -->
  <!-- TODO: Maybe this isn't good practice, and we should define environment variables for specific features (tuples, drawing, etc) instead? -->

  <ItemGroup Condition="'$(TargetFramework)'=='netstandard1.1'">
    <PackageReference Include="System.Drawing.Primitives" Version="4.3.0" />
    <PackageReference Include="System.Net.Http" Version="4.3.4" />                <!-- Version that comes with .NET has vulnerabilities. -->
    <PackageReference Include="System.Memory" Version="4.5.5" />                  <!-- Newer versions not supported. -->
    <PackageReference Include="System.Numerics.Vectors" Version="4.5.0" />        <!-- Newer versions not supported. -->
    <PackageReference Include="System.Text.RegularExpressions" Version="4.3.1" /> <!-- Version that comes with .NET has vulnerabilities. -->
    <PackageReference Include="System.ValueTuple" Version="4.5.0" />              <!-- Newer version not supported. -->
  </ItemGroup>
  
  <ItemGroup Condition="'$(TargetFramework)'=='netstandard1.3'">
    <PackageReference Include="System.Drawing.Primitives" Version="4.3.0" />
    <PackageReference Include="System.Net.Http" Version="4.3.4" />                <!-- Version that comes with .NET has vulnerabilities. -->
    <PackageReference Include="System.Memory" Version="4.5.5" />                  <!-- Newer versions not supported. -->
    <PackageReference Include="System.Numerics.Vectors" Version="4.5.0" />        <!-- Newer versions not supported. -->
    <PackageReference Include="System.Text.RegularExpressions" Version="4.3.1" /> <!-- Version that comes with .NET has vulnerabilities. -->
    <PackageReference Include="System.ValueTuple" Version="4.5.0" />              <!-- Newer version not supported. -->
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)'=='net46'">
    <PackageReference Include="System.Memory" Version="4.5.5" />                  <!-- Newer versions not supported. -->
    <PackageReference Include="System.ValueTuple" Version="4.5.0" />              <!-- Newer versions not supported. -->
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)'=='net462'">
    <PackageReference Include="System.Memory" Version="4.6.2" />
    <PackageReference Include="System.ValueTuple" Version="4.6.1" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)'=='net47'">
    <PackageReference Include="System.Memory" Version="4.6.2" />
  </ItemGroup>
  
  <!-- PropertyGroup customization based on framework. -->
  <!-- Used to define environment variables based on features the framework supports. -->

  <PropertyGroup Condition="'$(TargetFramework)'=='netstandard1.1'">
    <DefineConstants>$(DefineConstants);CS7_OR_GREATER</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)'=='netstandard1.3'">
    <DefineConstants>$(DefineConstants);CS7_OR_GREATER</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)'=='netstandard2.1'">
    <DefineConstants>$(DefineConstants);CS7_OR_GREATER;CS8_OR_GREATER</DefineConstants>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)'=='net46'">
    <DefineConstants>$(DefineConstants);CS7_OR_GREATER</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)'=='net462'">
    <DefineConstants>$(DefineConstants);CS7_OR_GREATER</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)'=='net47'">
    <DefineConstants>$(DefineConstants);CS7_OR_GREATER</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)'=='netcoreapp3.0'">
    <DefineConstants>$(DefineConstants);CS7_OR_GREATER;CS8_OR_GREATER</DefineConstants>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)'=='net5.0'">
    <DefineConstants>$(DefineConstants);CS7_OR_GREATER;CS8_OR_GREATER;CS9_OR_GREATER</DefineConstants>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup Condition="'$(TargetFramework)'=='net7.0'">
    <DefineConstants>$(DefineConstants);CS7_OR_GREATER;CS8_OR_GREATER;CS9_OR_GREATER;CS10_OR_GREATER;CS11_OR_GREATER</DefineConstants>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  
  <!-- Pack extra stuff into the NuGet package. -->

  <ItemGroup>
    <None Include="..\Extras\Logo Square.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\LICENSE.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
